apiVersion: apps/v1
kind: Deployment
metadata:
  name: platforms-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-service
  template:
    metadata:
      labels:
        app: platform-service
    spec:
      containers:
        - name: platform-service-app
          image: gm50x/platformservice
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: platforms-svc
spec:
  type: NodePort
  selector:
    app: platform-service
  ports:
    - name: platforms-service-http
      protocol: TCP
      port: 8080
      targetPort: 8080
