apiVersion: apps/v1
kind: Deployment
metadata:
  name: platforms-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platforms-service
  template:
    metadata:
      labels:
        app: platforms-service
    spec:
      containers:
        - name: platforms-service-app
          image: gm50x/platformservice
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: DB_SERVER
              value: "mssql-clusterip-srv"
            - name: DB_USER
              value: "sa"
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mssql
                  key: SA_PASSWORD
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: platforms-clusterip-svc
spec:
  type: ClusterIP
  selector:
    app: platforms-service
  ports:
    - name: platforms-service-http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: platforms-service-grpc
      protocol: TCP
      port: 8888
      targetPort: 8888

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: commands-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commands-service
  template:
    metadata:
      labels:
        app: commands-service
    spec:
      containers:
        - name: commands-service-app
          image: gm50x/commandservice
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: commands-clusterip-svc
spec:
  type: ClusterIP
  selector:
    app: commands-service
  ports:
    - name: commands-service-http
      protocol: TCP
      port: 8080
      targetPort: 8080
---
## helm upgrade --install ingress-nginx ingress-nginx \
## --repo https://kubernetes.github.io/ingress-nginx \
##  --namespace ingress-nginx --create-namespace
## OR:
## kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.2/deploy/static/provider/cloud/deploy.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: gedai.local
      http:
        paths:
          - pathType: Prefix
            path: "/api/platforms"
            backend:
              service:
                name: platforms-clusterip-svc
                port:
                  number: 8080
          - pathType: Prefix
            path: "/api/c/platforms"
            backend:
              service:
                name: commands-clusterip-svc
                port:
                  number: 8080
