apiVersion: apps/v1
kind: Deployment
metadata:
  name: platforms-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platforms-service
  template:
    metadata:
      labels:
        app: platforms-service
    spec:
      containers:
        - name: platforms-service-app
          image: gm50x/platformservice
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: platforms-svc
spec:
  type: NodePort
  selector:
    app: platforms-service
  ports:
    - name: platforms-service-http
      protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: platforms-clusterip-svc
spec:
  type: ClusterIP
  selector:
    app: platforms-service
  ports:
    - name: platforms-service-http
      protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: commands-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commands-service
  template:
    metadata:
      labels:
        app: commands-service
    spec:
      containers:
        - name: commands-service-app
          image: gm50x/commandservice
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: commands-clusterip-svc
spec:
  type: ClusterIP
  selector:
    app: commands-service
  ports:
    - name: commands-service-http
      protocol: TCP
      port: 8080
      targetPort: 8080
